import type { ResponsivePictureImageProps } from "@/components/ResponsivePicture/ResponsivePicture";

export interface ImageData {
  [key: string]: {
    [key: string]: ResponsivePictureImageProps;
  };
}
export const IMAGE_DATA: ImageData = {
  iPadPro: {
    xlarge_2x: {
      viewport: "xlarge",
      density: 2,
      width: 592,
      height: 680,
      src: "assets/product-tile/ipad-pro/ipad_pro_xlarge_2x.png",
    },
    xlarge: {
      viewport: "xlarge",
      density: 1,
      width: 296,
      height: 340,
      src: "assets/product-tile/ipad-pro/ipad_pro_xlarge.png",
    },
    large_2x: {
      viewport: "large",
      density: 2,
      width: 534,
      height: 614,
      src: "assets/product-tile/ipad-pro/ipad_pro_large_2x.png",
    },
    large: {
      viewport: "large",
      density: 1,
      width: 267,
      height: 307,
      src: "assets/product-tile/ipad-pro/ipad_pro_large.png",
    },
    medium_2x: {
      viewport: "medium",
      density: 2,
      width: 492,
      height: 566,
      src: "assets/product-tile/ipad-pro/ipad_pro_medium_2x.png",
    },
    medium: {
      viewport: "medium",
      density: 1,
      width: 246,
      height: 283,
      src: "assets/product-tile/ipad-pro/ipad_pro_medium.png",
    },
    small_2x: {
      viewport: "small",
      density: 2,
      width: 356,
      height: 402,
      src: "assets/product-tile/ipad-pro/ipad_pro_small.png",
    },
    small: {
      viewport: "small",
      density: 1,
      width: 178,
      height: 201,
      src: "assets/product-tile/ipad-pro/ipad_pro_small.png",
    },
    xsmall_2x: {
      viewport: "xsmall",
      density: 2,
      width: 356,
      height: 402,
      src: "assets/product-tile/ipad-pro/ipad_pro_small_2x.png",
    },
    xsmall: {
      viewport: "xsmall",
      density: 1,
      width: 178,
      height: 201,
      src: "assets/product-tile/ipad-pro/ipad_pro_small.png",
    },
  },
  iPadAir: {
    xlarge_2x: {
      viewport: "xlarge",
      density: 2,
      width: 592,
      height: 680,
      src: "assets/product-tile/ipad-air/ipad_air_xlarge_2x.png",
    },
    xlarge: {
      viewport: "xlarge",
      density: 1,
      width: 296,
      height: 340,
      src: "assets/product-tile/ipad-air/ipad_air_xlarge.png",
    },
    large_2x: {
      viewport: "large",
      density: 2,
      width: 534,
      height: 614,
      src: "assets/product-tile/ipad-air/ipad_air_large_2x.png",
    },
    large: {
      viewport: "large",
      density: 1,
      width: 267,
      height: 307,
      src: "assets/product-tile/ipad-air/ipad_air_large.png",
    },
    medium_2x: {
      viewport: "medium",
      density: 2,
      width: 492,
      height: 566,
      src: "assets/product-tile/ipad-air/ipad_air_medium_2x.png",
    },
    medium: {
      viewport: "medium",
      density: 1,
      width: 246,
      height: 283,
      src: "assets/product-tile/ipad-air/ipad_air_medium.png",
    },
    small_2x: {
      viewport: "small",
      density: 2,
      width: 356,
      height: 402,
      src: "assets/product-tile/ipad-air/ipad_air_small_2x.png",
    },
    small: {
      viewport: "small",
      density: 1,
      width: 178,
      height: 201,
      src: "assets/product-tile/ipad-air/ipad_air_small.png",
    },
    xsmall_2x: {
      viewport: "xsmall",
      density: 2,
      width: 356,
      height: 402,
      src: "assets/product-tile/ipad-air/ipad_air_small_2x.png",
    },
    xsmall: {
      viewport: "xsmall",
      density: 1,
      width: 178,
      height: 201,
      src: "assets/product-tile/ipad-air/ipad_air_small.png",
    },
  },
  iPadMini: {
    xlarge_2x: {
      viewport: "xlarge",
      density: 2,
      width: 334,
      height: 680,
      src: "assets/product-tile/ipad-mini/ipad_mini_xlarge_2x.png",
    },
    xlarge: {
      viewport: "xlarge",
      density: 1,
      width: 167,
      height: 340,
      src: "assets/product-tile/ipad-mini/ipad_mini_xlarge.png",
    },
    large_2x: {
      viewport: "large",
      density: 2,
      width: 302,
      height: 614,
      src: "assets/product-tile/ipad-mini/ipad_mini_large_2x.png",
    },
    large: {
      viewport: "large",
      density: 1,
      width: 151,
      height: 307,
      src: "assets/product-tile/ipad-mini/ipad_mini_large.png",
    },
    medium_2x: {
      viewport: "medium",
      density: 2,
      width: 278,
      height: 566,
      src: "assets/product-tile/ipad-mini/ipad_mini_medium_2x.png",
    },
    medium: {
      viewport: "medium",
      density: 1,
      width: 139,
      height: 283,
      src: "assets/product-tile/ipad-mini/ipad_mini_medium.png",
    },
    small_2x: {
      viewport: "small",
      density: 2,
      width: 198,
      height: 402,
      src: "assets/product-tile/ipad-mini/ipad_mini_small_2x.png",
    },
    small: {
      viewport: "small",
      density: 1,
      width: 149,
      height: 201,
      src: "assets/product-tile/ipad-mini/ipad_mini_small.png",
    },
    xsmall_2x: {
      viewport: "xsmall",
      density: 2,
      width: 198,
      height: 402,
      src: "assets/product-tile/ipad-mini/ipad_mini_small_2x.png",
    },
    xsmall: {
      viewport: "xsmall",
      density: 1,
      width: 149,
      height: 201,
      src: "assets/product-tile/ipad-mini/ipad_mini_small.png",
    },
  },
  iPad_10gen: {
    xlarge_2x: {
      viewport: "xlarge",
      density: 2,
      width: 432,
      height: 680,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_xlarge_2x.png",
    },
    xlarge: {
      viewport: "xlarge",
      density: 1,
      width: 216,
      height: 340,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_xlarge.png",
    },
    large_2x: {
      viewport: "large",
      density: 2,
      width: 390,
      height: 614,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_large_2x.png",
    },
    large: {
      viewport: "large",
      density: 1,
      width: 195,
      height: 307,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_large.png",
    },
    medium_2x: {
      viewport: "medium",
      density: 2,
      width: 360,
      height: 566,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_medium_2x.png",
    },
    medium: {
      viewport: "medium",
      density: 1,
      width: 128,
      height: 283,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_medium.png",
    },
    small_2x: {
      viewport: "small",
      density: 2,
      width: 256,
      height: 402,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_small_2x.png",
    },
    small: {
      viewport: "small",
      density: 1,
      width: 178,
      height: 201,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_small.png",
    },
    xsmall_2x: {
      viewport: "xsmall",
      density: 2,
      width: 256,
      height: 402,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_small_2x.png",
    },
    xsmall: {
      viewport: "xsmall",
      density: 1,
      width: 178,
      height: 201,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_small.png",
    },
  },
};
