import type { ResponsivePictureImageProps } from "@/components/ResponsivePicture/ResponsivePicture";

export interface ImageData {
  [key: string]: {
    [key: string]: ResponsivePictureImageProps;
  };
}
export const IMAGE_DATA: ImageData = {
  iPadPro: {
    xlarge_2x: {
      viewport: "xlarge",
      density: 2,
      width: 600,
      height: 680,
      src: "assets/product-tile/ipad-pro/ipad_pro_xlarge_2x.png",
    },
    xlarge: {
      viewport: "xlarge",
      density: 1,
      width: 300,
      height: 340,
      src: "assets/product-tile/ipad-pro/ipad_pro_xlarge.png",
    },
    large_2x: {
      viewport: "large",
      density: 2,
      width: 546,
      height: 618,
      src: "assets/product-tile/ipad-pro/ipad_pro_large_2x.png",
    },
    large: {
      viewport: "large",
      density: 1,
      width: 273,
      height: 309,
      src: "assets/product-tile/ipad-pro/ipad_pro_large.png",
    },
    medium_2x: {
      viewport: "medium",
      density: 2,
      width: 504,
      height: 572,
      src: "assets/product-tile/ipad-pro/ipad_pro_medium_2x.png",
    },
    medium: {
      viewport: "medium",
      density: 1,
      width: 252,
      height: 286,
      src: "assets/product-tile/ipad-pro/ipad_pro_medium.png",
    },
    small_2x: {
      viewport: "small",
      density: 2,
      width: 426,
      height: 482,
      src: "assets/product-tile/eqHeight/ipad_pro_2x.png",
    },
    small: {
      viewport: "small",
      density: 1,
      width: 213,
      height: 241,
      src: "assets/product-tile/ipad-pro/ipad_pro_small.png",
    },
    xsmall_2x: {
      viewport: "xsmall",
      density: 2,
      width: 360,
      height: 408,
      src: "assets/product-tile/ipad-pro/ipad_pro_small_2x.png",
    },
    xsmall: {
      viewport: "xsmall",
      density: 1,
      width: 180,
      height: 204,
      src: "assets/product-tile/ipad-pro/ipad_pro_small.png",
    },
  },
  iPadAir: {
    xlarge_2x: {
      viewport: "xlarge",
      density: 2,
      width: 432,
      height: 680,
      src: "assets/product-tile/ipad-air/ipad_air_xlarge_2x.png",
    },
    xlarge: {
      viewport: "xlarge",
      density: 1,
      width: 216,
      height: 340,
      src: "assets/product-tile/ipad-air/ipad_air_xlarge.png",
    },
    large_2x: {
      viewport: "large",
      density: 2,
      width: 394,
      height: 618,
      src: "assets/product-tile/ipad-air/ipad_air_large_2x.png",
    },
    large: {
      viewport: "large",
      density: 1,
      width: 197,
      height: 309,
      src: "assets/product-tile/ipad-air/ipad_air_large.png",
    },
    medium_2x: {
      viewport: "medium",
      density: 2,
      width: 362,
      height: 572,
      src: "assets/product-tile/ipad-air/ipad_air_medium_2x.png",
    },
    medium: {
      viewport: "medium",
      density: 1,
      width: 181,
      height: 286,
      src: "assets/product-tile/ipad-air/ipad_air_medium.png",
    },
    small_2x: {
      viewport: "small",
      density: 2,
      width: 306,
      height: 482,
      src: "assets/product-tile/ipad-air/ipad_air_small_2x.png",
    },
    small: {
      viewport: "small",
      density: 1,
      width: 153,
      height: 241,
      src: "assets/product-tile/ipad-air/ipad_air_small.png",
    },
    xsmall_2x: {
      viewport: "xsmall",
      density: 2,
      width: 260,
      height: 408,
      src: "assets/product-tile/ipad-air/ipad_air_small_2x.png",
    },
    xsmall: {
      viewport: "xsmall",
      density: 1,
      width: 130,
      height: 204,
      src: "assets/product-tile/ipad-air/ipad_air_small.png",
    },
  },
  iPadMini: {
    xlarge_2x: {
      viewport: "xlarge",
      density: 2,
      width: 334,
      height: 680,
      src: "/assets/product-tile/ipad-mini/ipad_mini_xlarge_2x.png",
    },
    xlarge: {
      viewport: "xlarge",
      density: 1,
      width: 167,
      height: 340,
      src: "/assets/product-tile/ipad-mini/ipad_mini_xlarge.png",
    },
    large_2x: {
      viewport: "large",
      density: 2,
      width: 304,
      height: 618,
      src: "/assets/product-tile/ipad-mini/ipad_mini_large_2x.png",
    },
    large: {
      viewport: "large",
      density: 1,
      width: 152,
      height: 309,
      src: "/assets/product-tile/ipad-mini/ipad_mini_large.png",
    },
    medium_2x: {
      viewport: "medium",
      density: 2,
      width: 280,
      height: 572,
      src: "/assets/product-tile/ipad-mini/ipad_mini_medium_2x.png",
    },
    medium: {
      viewport: "medium",
      density: 1,
      width: 140,
      height: 286,
      src: "/assets/product-tile/ipad-mini/ipad_mini_medium.png",
    },
    small_2x: {
      viewport: "small",
      density: 2,
      width: 238,
      height: 482,
      src: "/assets/product-tile/ipad-mini/ipad_mini_2x.png",
    },
    small: {
      viewport: "small",
      density: 1,
      width: 119,
      height: 241,
      src: "/assets/product-tile/ipad-mini/ipad_mini_small.png",
    },
    xsmall_2x: {
      viewport: "xsmall",
      density: 2,
      width: 200,
      height: 408,
      src: "/assets/product-tile/ipad-mini/ipad_mini_small_2x.png",
    },
    xsmall: {
      viewport: "xsmall",
      density: 1,
      width: 100,
      height: 204,
      src: "/assets/product-tile/ipad-mini/ipad_mini_small.png",
    },
  },
  iPad_9gen: {
    xlarge_2x: {
      viewport: "xlarge",
      density: 2,
      width: 416,
      height: 680,
      src: "assets/product-tile/eqHeight/ipad_gen9_2x.png",
    },
    xlarge: {
      viewport: "xlarge",
      density: 1,
      width: 208,
      height: 340,
      src: "assets/product-tile/eqHeight/ipad_gen9.png",
    },
    large_2x: {
      viewport: "large",
      density: 2,
      width: 378,
      height: 618,
      src: "assets/product-tile/eqHeight/ipad_gen9_2x.png",
    },
    large: {
      viewport: "large",
      density: 1,
      width: 189,
      height: 309,
      src: "assets/product-tile/eqHeight/ipad_gen9.png",
    },
    medium_2x: {
      viewport: "medium",
      density: 2,
      width: 350,
      height: 572,
      src: "assets/product-tile/eqHeight/ipad_gen9_2x.png",
    },
    medium: {
      viewport: "medium",
      density: 1,
      width: 175,
      height: 286,
      src: "assets/product-tile/eqHeight/ipad_gen9.png",
    },
    small_2x: {
      viewport: "small",
      density: 2,
      width: 296,
      height: 482,
      src: "assets/product-tile/eqHeight/ipad_gen9_2x.png",
    },
    small: {
      viewport: "small",
      density: 1,
      width: 148,
      height: 241,
      src: "assets/product-tile/eqHeight/ipad_gen9.png",
    },
    xsmall_2x: {
      viewport: "xsmall",
      density: 2,
      width: 250,
      height: 408,
      src: "assets/product-tile/eqHeight/ipad_gen9_2x.png",
    },
    xsmall: {
      viewport: "xsmall",
      density: 1,
      width: 125,
      height: 204,
      src: "assets/product-tile/eqHeight/ipad_gen9.png",
    },
  },
  iPad_10gen: {
    xlarge_2x: {
      viewport: "xlarge",
      density: 2,
      width: 432,
      height: 680,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_xlarge_2x.png",
    },
    xlarge: {
      viewport: "xlarge",
      density: 1,
      width: 216,
      height: 340,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_xlarge.png",
    },
    large_2x: {
      viewport: "large",
      density: 2,
      width: 394,
      height: 618,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_large_2x.png",
    },
    large: {
      viewport: "large",
      density: 1,
      width: 197,
      height: 309,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_large.png",
    },
    medium_2x: {
      viewport: "medium",
      density: 2,
      width: 362,
      height: 572,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_medium_2x.png",
    },
    medium: {
      viewport: "medium",
      density: 1,
      width: 181,
      height: 286,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_medium.png",
    },
    small_2x: {
      viewport: "small",
      density: 2,
      width: 306,
      height: 482,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_small_2x.png",
    },
    small: {
      viewport: "small",
      density: 1,
      width: 153,
      height: 241,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_small.png",
    },
    xsmall_2x: {
      viewport: "xsmall",
      density: 2,
      width: 260,
      height: 408,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_small_2x.png",
    },
    xsmall: {
      viewport: "xsmall",
      density: 1,
      width: 130,
      height: 204,
      src: "assets/product-tile/ipad_10gen/ipad_10th_gen_small.png",
    },
  },
};
