import type { ResponsivePictureImageProps } from "@/components/ResponsivePicture/ResponsivePicture";

export interface ImageData {
  [key: string]: {
    [key: string]: ResponsivePictureImageProps;
  };
}

export const IMAGE_DATA: ImageData = {
  productivity: {
    xlarge_2x: {
      viewport: "xlarge",
      density: 2,
      width: 810,
      height: 1608,
      src: "/assets/feature-card/productivity/feature-card-productivity_xlarge_2x.jpg",
    },
    xlarge: {
      viewport: "xlarge",
      density: 1,
      width: 405,
      height: 804,
      src: "/assets/feature-card/productivity/feature-card-productivity_xlarge.jpg",
    },
    large_2x: {
      viewport: "large",
      density: 2,
      width: 744,
      height: 1488,
      src: "/assets/feature-card/productivity/feature-card-productivity_large_2x.jpg",
    },
    large: {
      viewport: "large",
      density: 1,
      width: 372,
      height: 744,
      src: "/assets/feature-card/productivity/feature-card-productivity_large.jpg",
    },
    medium_2x: {
      viewport: "medium",
      density: 2,
      width: 688,
      height: 1368,
      src: "/assets/feature-card/productivity/feature-card-productivity_medium_2x.jpg",
    },
    medium: {
      viewport: "medium",
      density: 1,
      width: 344,
      height: 684,
      src: "/assets/feature-card/productivity/feature-card-productivity_medium.jpg",
    },
    small_2x: {
      viewport: "small",
      density: 2,
      width: 608,
      height: 1220,
      src: "/assets/feature-card/productivity/feature-card-productivity_small_2x.jpg",
    },
    small: {
      viewport: "small",
      density: 1,
      width: 304,
      height: 610,
      src: "/assets/feature-card/productivity/feature-card-productivity_small.jpg",
    },

    xsmall_2x: {
      viewport: "xsmall",
      density: 2,
      width: 520,
      height: 1260,
      src: "/assets/feature-card/productivity/feature-card-productivity_xsmall_2x.jpg",
    },
    xsmall: {
      viewport: "xsmall",
      density: 1,
      width: 260,
      height: 630,
      src: "/assets/feature-card/productivity/feature-card-productivity_xsmall_2x.jpg",
    },
  },
  creativity: {
    xlarge_2x: {
      viewport: "xlarge",
      density: 2,
      width: 810,
      height: 1608,
      src: "/assets/feature-card/creativity/feature-card-creativity_xlarge_2x.jpg",
    },
    xlarge: {
      viewport: "xlarge",
      density: 1,
      width: 405,
      height: 804,
      src: "/assets/feature-card/creativity/feature-card-creativity_xlarge.jpg",
    },
    large_2x: {
      viewport: "large",
      density: 2,
      width: 744,
      height: 1488,
      src: "/assets/feature-card/creativity/feature-card-creativity_large_2x.jpg",
    },
    large: {
      viewport: "large",
      density: 1,
      width: 372,
      height: 744,
      src: "/assets/feature-card/creativity/feature-card-creativity_large.jpg",
    },
    medium_2x: {
      viewport: "medium",
      density: 2,
      width: 688,
      height: 1368,
      src: "/assets/feature-card/creativity/feature-card-creativity_medium_2x.jpg",
    },
    medium: {
      viewport: "medium",
      density: 1,
      width: 344,
      height: 684,
      src: "/assets/feature-card/creativity/feature-card-creativity_medium.jpg",
    },
    small_2x: {
      viewport: "small",
      density: 2,
      width: 608,
      height: 1220,
      src: "/assets/feature-card/creativity/feature-card-creativity_small_2x.jpg",
    },
    small: {
      viewport: "small",
      density: 1,
      width: 304,
      height: 610,
      src: "/assets/feature-card/creativity/feature-card-creativity_small.jpg",
    },

    xsmall_2x: {
      viewport: "xsmall",
      density: 2,
      width: 520,
      height: 1260,
      src: "/assets/feature-card/creativity/feature-card-creativity_xsmall_2x.jpg",
    },
    xsmall: {
      viewport: "xsmall",
      density: 1,
      width: 260,
      height: 630,
      src: "/assets/feature-card/creativity/feature-card-creativity_xsmall_2x.jpg",
    },
  },
  learning: {
    xlarge_2x: {
      viewport: "xlarge",
      density: 2,
      width: 810,
      height: 1608,
      src: "/assets/feature-card/learning/feature-card-ipados_xlarge_2x.jpg",
    },
    xlarge: {
      viewport: "xlarge",
      density: 1,
      width: 405,
      height: 804,
      src: "/assets/feature-card/learning/feature-card-ipados_xlarge.jpg",
    },
    large_2x: {
      viewport: "large",
      density: 2,
      width: 744,
      height: 1488,
      src: "/assets/feature-card/learning/feature-card-ipados_large_2x.jpg",
    },
    large: {
      viewport: "large",
      density: 1,
      width: 372,
      height: 744,
      src: "/assets/feature-card/learning/feature-card-ipados_large.jpg",
    },
    medium_2x: {
      viewport: "medium",
      density: 2,
      width: 688,
      height: 1368,
      src: "/assets/feature-card/learning/feature-card-ipados_medium_2x.jpg",
    },
    medium: {
      viewport: "medium",
      density: 1,
      width: 344,
      height: 684,
      src: "/assets/feature-card/learning/feature-card-ipados_medium.jpg",
    },
    small_2x: {
      viewport: "small",
      density: 2,
      width: 608,
      height: 1220,
      src: "/assets/feature-card/learning/feature-card-ipados_small_2x.jpg",
    },
    small: {
      viewport: "small",
      density: 1,
      width: 304,
      height: 610,
      src: "/assets/feature-card/learning/feature-card-ipados_small.jpg",
    },

    xsmall_2x: {
      viewport: "xsmall",
      density: 2,
      width: 520,
      height: 1260,
      src: "/assets/feature-card/learning/feature-card-ipados_xsmall_2x.jpg",
    },
    xsmall: {
      viewport: "xsmall",
      density: 1,
      width: 260,
      height: 630,
      src: "/assets/feature-card/learning/feature-card-ipados_xsmall_2x.jpg",
    },
  },
  pencil: {
    xlarge_2x: {
      viewport: "xlarge",
      density: 2,
      width: 810,
      height: 1608,
      src: "/assets/feature-card/pencil/feature-card-pencil_xlarge_2x.jpg",
    },
    xlarge: {
      viewport: "xlarge",
      density: 1,
      width: 405,
      height: 804,
      src: "/assets/feature-card/pencil/feature-card-pencil_xlarge.jpg",
    },
    large_2x: {
      viewport: "large",
      density: 2,
      width: 744,
      height: 1488,
      src: "/assets/feature-card/pencil/feature-card-pencil_large_2x.jpg",
    },
    large: {
      viewport: "large",
      density: 1,
      width: 372,
      height: 744,
      src: "/assets/feature-card/pencil/feature-card-pencil_large.jpg",
    },
    medium_2x: {
      viewport: "medium",
      density: 2,
      width: 688,
      height: 1368,
      src: "/assets/feature-card/pencil/feature-card-pencil_medium_2x.jpg",
    },
    medium: {
      viewport: "medium",
      density: 1,
      width: 344,
      height: 684,
      src: "/assets/feature-card/pencil/feature-card-pencil_medium.jpg",
    },
    small_2x: {
      viewport: "small",
      density: 2,
      width: 608,
      height: 1220,
      src: "/assets/feature-card/pencil/feature-card-pencil_small_2x.jpg",
    },
    small: {
      viewport: "small",
      density: 1,
      width: 304,
      height: 610,
      src: "/assets/feature-card/pencil/feature-card-pencil_small.jpg",
    },

    xsmall_2x: {
      viewport: "xsmall",
      density: 2,
      width: 520,
      height: 1260,
      src: "/assets/feature-card/pencil/feature-card-pencil_xsmall_2x.jpg",
    },
    xsmall: {
      viewport: "xsmall",
      density: 1,
      width: 260,
      height: 630,
      src: "/assets/feature-card/pencil/feature-card-pencil_xsmall_2x.jpg",
    },
  },
};

export const DARK_IMG_DATA = {
  xsmall: {
    viewport: "xsmall",
    density: 1,
    width: 260,
    height: 530,
    src: "./assets/feature-card/dark/feature_card_dark_xsmall.jpg",
    backgroundColor: "rgba(255,255,255,0.88)",
  },
  xsmall_2x: {
    viewport: "xsmall",
    density: 2,
    width: 520,
    height: 1060,
    src: "./assets/feature-card/dark/feature_card_dark_xsmall.jpg",
    backgroundColor: "rgba(255,255,255,0.88)",
  },
  small: {
    viewport: "small",
    density: 1,
    width: 304,
    height: 610,
    src: "./assets/feature-card/dark/feature_card_dark_small.jpg",
    backgroundColor: "rgba(255,255,255,0.88)",
  },
  small_2x: {
    viewport: "small",
    density: 2,
    width: 608,
    height: 1220,
    src: "./assets/feature-card/dark/feature_card_dark_small_2x.jpg",
    backgroundColor: "rgba(255,255,255,0.88)",
  },
  medium: {
    viewport: "medium",
    density: 1,
    width: 344,
    height: 684,
    src: "./assets/feature-card/dark/feature_card_dark_medium.jpg",
    backgroundColor: "#ff0000",
  },
  medium_2x: {
    viewport: "medium",
    density: 2,
    width: 688,
    height: 1368,
    src: "./assets/feature-card/dark/feature_card_dark_medium_2x.jpg",
  },
  large: {
    viewport: "large",
    density: 1,
    width: 372,
    height: 744,
    src: "./assets/feature-card/dark/feature_card_dark_large.jpg",
  },
  large_2x: {
    viewport: "large",
    density: 2,
    width: 744,
    height: 1488,
    src: "./assets/feature-card/dark/feature_card_dark_large_2x.jpg",
  },
  xlarge: {
    viewport: "xlarge",
    density: 1,
    width: 405,
    height: 804,
    src: "./assets/feature-card/dark/feature_card_dark_xlarge.jpg",
  },
  xlarge_2x: {
    viewport: "xlarge",
    density: 2,
    width: 810,
    height: 1608,
    src: "./assets/feature-card/dark/feature_card_dark_xlarge_2x.jpg",
  },
};
