export const PENCIL_IMG_DATA = {
  xlarge_2x: {
    viewport: "xlarge",
    density: 2,
    width: 1660,
    height: 824,
    src: "/assets/essential-card/essential_card_pencil_xlarge_2x.jpg",
  },
  xlarge: {
    viewport: "xlarge",
    density: 1,
    width: 830,
    height: 412,
    src: "/assets/essential-card/essential_card_pencil_xlarge.jpg",
  },
  large_2x: {
    viewport: "large",
    density: 2,
    width: 1240,
    height: 702,
    src: "/assets/essential-card/essential_card_pencil_large_2x.jpg",
  },
  large: {
    viewport: "large",
    density: 1,
    width: 620,
    height: 351,
    src: "/assets/essential-card/essential_card_pencil_large.jpg",
  },
  medium_2x: {
    viewport: "medium",
    density: 2,
    width: 914,
    height: 712,
    src: "/assets/essential-card/essential_card_pencil_medium_2x.jpg",
  },
  medium: {
    viewport: "medium",
    density: 1,
    width: 457,
    height: 356,
    src: "/assets/essential-card/essential_card_pencil_medium.jpg",
  },
  small_2x: {
    viewport: "small",
    density: 2,
    width: 622,
    height: 760,
    src: "/assets/essential-card/essential_card_pencil_small_2x.jpg",
  },
  small: {
    viewport: "small",
    density: 1,
    width: 311,
    height: 380,
    src: "/assets/essential-card/essential_card_pencil_small.jpg",
  },
  xsmall_2x: {
    viewport: "xsmall",
    density: 2,
    width: 560,
    height: 602,
    src: "/assets/essential-card/essential_card_pencil_xsmall_2x.jpg",
  },
  xsmall: {
    viewport: "xsmall",
    density: 1,
    width: 280,
    height: 301,
    src: "/assets/essential-card/essential_card_pencil_xsmall.jpg",
  },
};

export const KEYBOARD_IMG_DATA = {
  xlarge_2x: {
    viewport: "xlarge",
    density: 2,
    width: 1120,
    height: 888,
    src: "/assets/essential-card/essential_card_keyboard_xlarge_2x.jpg",
  },
  xlarge: {
    viewport: "xlarge",
    density: 1,
    width: 560,
    height: 444,
    src: "/assets/essential-card/essential_card_keyboard_xlarge.jpg",
  },
  large_2x: {
    viewport: "large",
    density: 2,
    width: 920,
    height: 754,
    src: "/assets/essential-card/essential_card_keyboard_large_2x.jpg",
  },
  large: {
    viewport: "large",
    density: 1,
    width: 460,
    height: 377,
    src: "/assets/essential-card/essential_card_keyboard_large.jpg",
  },
  medium_2x: {
    viewport: "medium",
    density: 2,
    width: 900,
    height: 760,
    src: "/assets/essential-card/essential_card_keyboard_medium_2x.jpg",
  },
  medium: {
    viewport: "medium",
    density: 1,
    width: 450,
    height: 380,
    src: "/assets/essential-card/essential_card_keyboard_medium.jpg",
  },
  small_2x: {
    viewport: "small",
    density: 2,
    width: 614,
    height: 822,
    src: "/assets/essential-card/essential_card_keyboard_small_2x.jpg",
  },
  small: {
    viewport: "small",
    density: 1,
    width: 307,
    height: 411,
    src: "/assets/essential-card/essential_card_keyboard_small.jpg",
  },
  xsmall_2x: {
    viewport: "xsmall",
    density: 2,
    width: 536,
    height: 638,
    src: "/assets/essential-card/essential_card_keyboard_xsmall.jpg",
  },
  xsmall: {
    viewport: "xsmall",
    density: 1,
    width: 268,
    height: 319,
    src: "/assets/essential-card/essential_card_keyboard_xsmall.jpg",
  },
};

export const HEIGHT_TEST_IMG_DATA = {
  xlarge_2x: {
    viewport: "xlarge",
    density: 2,
    width: 1500,
    height: 1500,
    src: "/assets/essential-card/ec_test_2x.jpg",
  },
  xlarge: {
    viewport: "xlarge",
    density: 1,
    width: 1500,
    height: 1500,
    src: "/assets/essential-card/ec_test.jpg",
  },
  large_2x: {
    viewport: "large",
    density: 2,
    width: 1500,
    height: 1500,
    src: "/assets/essential-card/ec_test_2x.jpg",
  },
  large: {
    viewport: "large",
    density: 1,
    width: 1500,
    height: 1500,
    src: "/assets/essential-card/ec_test.jpg",
  },
  medium_2x: {
    viewport: "medium",
    density: 2,
    width: 1500,
    height: 1500,
    src: "/assets/essential-card/ec_test_2x.jpg",
  },
  medium: {
    viewport: "medium",
    density: 1,
    width: 1500,
    height: 1500,
    src: "/assets/essential-card/ec_test.jpg",
  },
  small_2x: {
    viewport: "small",
    density: 2,
    width: 1500,
    height: 1500,
    src: "/assets/essential-card/ec_test_2x.jpg",
  },
  small: {
    viewport: "small",
    density: 1,
    width: 1500,
    height: 1500,
    src: "/assets/essential-card/ec_test.jpg",
  },
  xsmall_2x: {
    viewport: "xsmall",
    density: 2,
    width: 1500,
    height: 1500,
    src: "/assets/essential-card/ec_test_2x.jpg",
  },
  xsmall: {
    viewport: "xsmall",
    density: 1,
    width: 1500,
    height: 1500,
    src: "/assets/essential-card/ec_test.jpg",
  },
};
