import "./globals.css";
import localFont from "next/font/local";

const sfText = localFont({
  src: [
    {
      path: "../public/fonts/SFProText-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/SFProText-RegularItalic.woff2",
      weight: "400",
      style: "italic",
    },
  ],
  fallback: ["system-ui", "Helvetica Neue", "Helvetica", "Arial", "sans-serif"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={sfText.className}>
      <body>{children}</body>
    </html>
  );
}
